### ISSUE TITLE
Missing flipX and flipY in graphics.Spritemap

### ISSUE THREAD

**Issue by aprokurov** [HaxePunk/HaxePunk#590] opened 2018-04-25 02:37 UTC
- **HaxePunk version:** 4.0.1
- **Haxe version:** 3.4.7
- **OpenFL/Lime or NME version:** 2.9.1

In examples/classic/src/platformer/entities/Player.hx i found these lines of code:
```Haxe
if (velocity.x < 0)
		{
			sprite.flipX = true; // left
		}
		else if (velocity.x > 0)
		{
			sprite.flipX = false; // right
}
```
But  [Spritemap](http://haxepunk.com/documentation/api/haxepunk/graphics/Spritemap.html) doesn't have these var's, so it's impossible to compile that example and flip sprite

**Comment by bendmorris** [comment] 2018-04-25 02:40
It has them because it extends [`Image`](https://github.com/HaxePunk/HaxePunk/blob/dev/haxepunk/graphics/Image.hx).

**Comment by aprokurov** [comment] 2018-04-25 02:46
I looked at Image, but it's impossible to flip Spritemap, how i can flip it?
```Haxe
source/entities/Player.hx:56: characters 12-24 : haxepunk.graphics.Spritemap has no field flipX
```

**Comment by bendmorris** [comment] 2018-04-25 03:03
`flipX` and `flipY` were added in the dev branch. It looks like you may be building the examples out of the git repo but using the latest release version of HaxePunk. You need to `haxelib dev` to set your HaxePunk lib to the git version.

**Comment by bendmorris** [comment] 2018-04-25 14:47
Going to close this as this is confirmed working on dev; it's verified as part of the CI.

**Closed by bendmorris** 2018-04-25 14:47 UTC
