### ISSUE TITLE
haxepunk.input.Key "takes over" other classes

### ISSUE THREAD

**Issue by Jacic** [HaxePunk/HaxePunk#486] opened 2017-05-18 19:41 UTC
- **HaxePunk version:** git
- **Target(s):** Any
- **Haxe version:** 3.4.2
- **OpenFL/Lime or NME version:** OpenFL 5.0.0 and Lime 4.1.0

I was playing around with the latest git version of HaxePunk when I ran into this. This is a pretty bizarre bug, but I narrowed down the steps to reproduce.
I have a "globals" class called "G", which holds several public static variables I want other code to access.
I do something like `G.playing = true;` which works as expected.
It does *not* work as expected if `haxepunk.input.Key` is imported in the class I'm accessing G with, instead giving the following error:

`src/PlayScene.hx:126: characters 15-24 : haxepunk.input.Key has no field playing`

So it seems that G is being treated as the Key class for some reason.

**Comment by bendmorris** [comment] 2017-05-18 20:11
Wow, that is very strange. I'm definitely using static properties from other classes in files that import Key though, so there must be more to it. Does this only happen in one project? Can you boil it down to a one-file reproducible example?

**Comment by Jacic** [comment] 2017-05-18 20:23
I just made a simple program to demonstrate this.

```
//import haxepunk.input.Key;
import haxepunk.Scene;
 
class TitleScene extends Scene
{
	override public function new()
	{
		super();

		G.playing = true;
	}
}
```

```
class G
{
	public static var playing:Bool;
}
```

It works with the import Key statement commented out, but uncomment it and it won't compile.

**Comment by bendmorris** [comment] 2017-05-19 15:50
I was able to repro. A few things I've noticed:

- Happens with both Lime and NME so it's not specifically Lime magic.
- I suspected maybe a bug in the haxepunk.utils.Platform.run() macro since it's using onTypeNotFound, but commenting this out didn't make a difference. That makes me suspect a Haxe bug.
- It only happens when the class name is a single letter! `C`, `G` and `Q` show the problem. `Co`, `Consts`, `Defs` do not.

**Comment by bendmorris** [comment] 2017-05-19 15:55
I think I understand - all of these single letter names are defined as values of the Key abstract, so Key.G is overshadowing the G class. I'm not sure if this is defined behavior in Haxe so I'll raise it over there. A workaround would be to rename your class, but that's not a very satisfying answer.

**Comment by bendmorris** [comment] 2017-05-19 15:59
Reproducible example that doesn't use HaxePunk:

```
@:enum
abstract MyAbstract(Int)
{
    var Math = 123;
}

class MainScene extends Scene
{
    override public function new()
    {
        super();

        trace(Math.round(1.5));
    }
}
```

>Test.hx:11: characters 14-24 : MyAbstract has no field round

**Comment by Jacic** [comment] 2017-05-19 16:33
Yeah it definitely seems to be the name of the class that's the issue. As a short-term fix I'll change it, but the strange part is that this didn't happen until recently. Obviously it's inconvenient, as a lot of names that people might want to use are defined by other classes. Just from the Key class, I can easily see someone wanting to use a class called Home, Space, Escape, Control, etc and also importing the Key class.

**Comment by bendmorris** [comment] 2017-05-19 17:57
The recent change is that Key changed from a class to an abstract, so that's why it shows up recently. Since Haxe is case sensitive classes like Home, Space, etc. won't be an issue (only HOME or SPACE) but the single letter case is still pretty annoying.

**Comment by bendmorris** [comment] 2017-11-12 19:21
Going to close this as there isn't much we can do about it, apart from changing Key back to a class, and I'm OK with this tradeoff. On collision with your own single-letter class, some workarounds include:

- Reference your class using its fully-qualified name (`mypackage.J` vs. `J`.)
- Limit the number of files that have to import Key (good practice anyway, as HaxePunk lets you abstract away the specific controls using logical names.)
- Rename your class.

**Closed by bendmorris** 2017-11-12 19:21 UTC
