### ISSUE TITLE
Neko target crashes with "dead code elimination full"

### ISSUE THREAD

**Issue by T1mL3arn** [HaxePunk/HaxePunk#350] opened 2015-01-04 15:38 UTC
If I use ```<haxeflag name="-dce full" />``` I get this after launch Neko app
```
$nargs
Called from C:\HaxeToolkit\haxe\std/neko/_std/Type.hx line 102
Called from openfl/_v2/text/Font.hx line 114
Called from DefaultAssetLibrary.hx line 144
Called from DefaultAssetLibrary.hx line 32
Called from openfl/_v2/Assets.hx line 580
Called from ApplicationMain.hx line 87
Called from openfl/_v2/Lib.hx line 114
```
HaxePunk version is 2.5.3.

**Comment by Marc010** [comment] 2015-01-04 19:29
I can reproduce it on Windows 7 64bit/Neko with a minimal haxepunk project.
HaxePunk 2.53
lime 2.0.4
openfl 2.2.1
hxcpp 3.1.48
Haxe 3.1.3

It also crashes with an minimal openfl project so it's a problem on their side. You should open a issue at https://github.com/openfl/openfl and link to this thread.
The problem can also be resolved by using the default '-dce std' or removing all assets.

**Comment by MattTuttle** [comment] 2015-01-06 18:56
Yep, I think this has been an issue in OpenFL for a while. The asset creation doesn't play nicely with dead code elimination. You should at least be able to use dead code elimination on the standard library with `-dce=std`.

**Comment by Marc010** [comment] 2015-01-11 13:59
I did not test it but it looks like in the next openfl haxelib release the bug is fixed.

https://github.com/openfl/openfl/commit/de07fab294b2dd247ffb5cf22c1c3541111b60ef#diff-ede4dcf914c15c509bed6fab772767b4L705

**Comment by T1mL3arn** [comment] 2015-01-12 03:16
Now HaxePunk Test project is working on Neko with -dce full.

**Closed** 2015-02-10 14:15 UTC
Labels: upstream
