### ISSUE TITLE
Type not found : flash.display.OpenGLView

### ISSUE THREAD

**Issue by ZHANITEST** [HaxePunk/HaxePunk#625] opened 2019-09-19 18:27 UTC
- **HaxePunk version:** 4.0.1
- **Target(s):** neko, html5
- **Haxe version:** 3.4.7
- **OpenFL/Lime or NME version:** openfl: [8.9.5]/lime: [7.6.3]

Hi. I got some errors when I use it first.

# List of commands used
1. haxelib list
2. haxelib run HaxePunk setup *// Error: No such version  for library munit*
3. haxelib run HaxePunk new MyProject
4. cd MyProject
5. haxelib run lime test neko
6. haxelib run lime test html5

# CMD log
```
>haxelib list
HaxePunk: [4.0.1]
hxcpp: [4.0.52]
lime-samples: [7.0.0]
lime: [7.6.3]
mconsole: [1.6.0]
mcover: [2.2.1]
mlib: [2.0.3]
munit: [2.3.4]
openfl: [8.9.5]

>haxelib run HaxePunk setup
Error: No such version  for library munit
hxcpp is up to date
lime-samples is up to date

>haxelib run HaxePunk new MyProject
HaxePunk-icon.svg
project.xml
HaxePunk-icon.png
.vscode/
.vscode/completion-openfl.hxml
.vscode/launch.json.tpl
.vscode/extensions.json
.vscode/tasks.json
.vscode/settings.json
source/
source/MainScene.hx
source/Main.hx
assets/
assets/audio/
assets/audio/README.md
assets/HaxePunk.png
assets/graphics/
assets/graphics/README.md
assets/font/
assets/font/README.md
assets/HaxePunk.svg

>cd MyProject

>haxelib run lime test neko
C:/HaxeToolkit/haxe/lib/HaxePunk/4,0,1/backend/flash/haxepunk/_internal/FlashApp.hx:3: characters 7-31 : Type not found : flash.display.OpenGLView

>haxelib run lime test html5
C:/HaxeToolkit/haxe/lib/HaxePunk/4,0,1/backend/flash/haxepunk/_internal/FlashApp.hx:3: characters 7-31 : Type not found : flash.display.OpenGLView
```

In my guess, it had some problem about `2. haxelib run HaxePunk setup`.
I don't know why i got this message: `Error: No such version  for library munit`

I already installed manually `munit` from `haxelib install muint`.

**Comment by ZHANITEST** [comment] 2019-09-22 14:28
Its work when i change `OpenFL` to `NME`.

This is what i used it:
```
>haxelib list
HaxePunk: [4.0.1]
hxcpp: [4.0.52]
lime-samples: [7.0.0]
mconsole: [1.6.0]
mcover: [2.2.1]
mlib: [2.0.3]
munit: [2.3.4]
nme: [6.0.58]
```

**Comment by XANOZOID** [comment] 2019-09-26 21:58
Please use the HaxePunk git version, it should be compatible with the latest back-ends since we've updated them. You'll be able to use OpenFL with it.

Try

```
haxelib git HaxePunk https://github.com/HaxePunk/HaxePunk.git
```

**Comment by ZHANITEST** [comment] 2019-09-28 02:10
Hi @XANOZOID. Thank you for reply.

Sadly, I tried with openfl: [8.9.5] and lime: [7.6.3] that you said(HaxePunk:git version) about 2 weeks ago. And same result :(
But I will re-try that with OpenFL And Lime and share a result in here.

Thanks.

**Comment by XANOZOID** [comment] 2019-09-28 18:49
@ZHANITEST Just a few things 

1. I don't believe you need to do the HaxePunk setup. All it does is install some dependencies(Munit) and update OpenFL/Lime - which you probably already did.

2. As far as the Git version goes, that's my bad. You specifically need to specify the `dev` branch (this has the updated backends).
       - `haxelib git HaxePunk https://github.com/HaxePunk/HaxePunk.git dev` _(notice dev)_

3. What OS are you on?

After you try this again with dev branch you should be good. I'm also updating the HaxePunk website as we speak so hopefully, no one wonders into this again.

**Comment by ZHANITEST** [comment] 2019-09-29 15:44
Hi @XANOZOID 

> 1. I don't believe you need to do the HaxePunk setup. All it does is install some dependencies(Munit) and update OpenFL/Lime - which you probably already did.`

That's not. OF COURSE, I used `dev`  branch. It's mean I typed like this `haxelib git HaxePunk https://github.com/HaxePunk/HaxePunk.git dev`. I didn't say that, sorry.

+ Addition: I don't know why HaxePunk user's need to install staticly `munit`. It's look like a unittest framwork. Even I can't find about `munit`. The HaxePunk Manual don't say it: [#](http://haxepunk.com/documentation/tutorials/getting-started/)

> 2. As far as the Git version goes, that's my bad. You specifically need to specify the dev branch (this has the updated backends).

I think HaxePunk had some problem with `dev` branch now. Look:
```
> haxelib run HaxePunk new My
"Generating template.zip"
Called from ? line 1
Called from CLI.hx line 148
Called from CLI.hx line 10
Called from CLI.hx line 29
Called from CLI.hx line 42
Called from Project.hx line 85
Called from Project.hx line 97
Called from C:\ProgramData\chocolatey\lib\haxe\haxe_20180221160843_bb7b827a9\std/neko/_std/sys/io/File.hx line 50
Uncaught exception - [file_open,C:/HaxeToolkit/haxe/lib/HaxePunk/git/template.zip]
```

BUT, I couldn't get any error when I used `4.0.1`.

```
>haxelib remove HaxePunk
Library HaxePunk removed

C:\Users\Man\Desktop\Example>haxelib install HaxePunk
Downloading HaxePunk-4,0,1.zip...
Download complete : 2698596 bytes in 19.5s (134.7KB/s)
Installing HaxePunk...
  Current version is now 4.0.1
Done

C:\Users\Man\Desktop\Example>haxelib run HaxePunk new My
HaxePunk-icon.svg
project.xml
HaxePunk-icon.png
.vscode/
.vscode/completion-openfl.hxml
.vscode/launch.json.tpl
.vscode/extensions.json
.vscode/tasks.json
.vscode/settings.json
source/
source/MainScene.hx
source/Main.hx
assets/
assets/audio/
assets/audio/README.md
assets/HaxePunk.png
assets/graphics/
assets/graphics/README.md
assets/font/
assets/font/README.md
assets/HaxePunk.svg
```

> 3. What OS are you on?

Windows 10 x64
And I used A *[chocolaty](https://chocolatey.org/)* when I install a Haxe.


Thank you :-)

**Comment by matrefeytontias** [comment] 2019-09-30 20:36
Alright got it. Use the `dev` branch and specifically set OpenFL to version 8.9.1 and Lime to version 7.4.0 ; those are the last versions that work with our latest version of HaxePunk. Until then, I'll work on a more stable version of HaxePunk ; one that doesn't rely on internals like it does right now.

I pushed a quick fix to the `run.n` tool in the meantime, which should install the correct versions of the libs when you run `haxelib run HaxePunk setup`, given that you don't already have them installed.

I'll close this when I will have gotten rid of every internal stuff.

**Comment by matrefeytontias** [comment] 2019-10-02 18:19
Upon more research, I decided that this would be the final working state of HaxePunk. We are working on getting rid of every Flash/OpenFL/NME dependency and moving to a Kha backend ; we will make sure that the documentation and the website explicitely specify the working versions of OpenFL and Lime.

**Closed by matrefeytontias** 2019-10-02 18:19 UTC

**Comment by xavierstampslafont** [comment] 2020-04-29 02:46
I just got this issue when trying to set up HaxePunk. The commands I used: 
```
haxelib install HaxePunk
haxelib git HaxePunk https://github.com/HaxePunk/HaxePunk.git
haxelib run HaxePunk setup
haxelib run HaxePunk new MyProject
cd MyProject
lime test neko # build and run
```
And I get the same `Type not found : flash.display.OpenGLView`. 

I tried with these versions as previous comments suggested: 
- openfl 8.9.1
- lime 7.6.3
- haxepunk dev

Any suggestions?

**Comment by matrefeytontias** [comment] 2020-04-29 17:12
Cannot reproduce. Doing all the steps you said leads to a perfectly working test project. Make sure when running `haxelib run HaxePunk setup` that you say "no" to the command-line asking you if you want to revert lime to version 7.4.0 and you should be good.
