### ISSUE TITLE
Rich text spacing problem 

### ISSUE THREAD

**Issue by rpidstryhach** [HaxePunk/HaxePunk#368] opened 2015-06-01 09:50 UTC
Added new style:
`_text.addStyle("scaled", {size:_text.size * 2});`
and used it like this:
`_text.richText = "hello\n<scaled>bug</scaled>\nnew line";`
And I got this on Neko/Android:
![mxf4329kwfrd21lqimerb2o5bsxyxgeimjlpty53ij4](https://cloud.githubusercontent.com/assets/8464160/7910293/16a603ea-085c-11e5-9124-2a50800f95bf.png)

**Comment by scriptorum** [comment] 2015-06-02 06:26
Do you have leading on your example? When I try this, on native or neko I get this (flash on left):
![screen shot 2015-06-02 at 2 11 12 am copy](https://cloud.githubusercontent.com/assets/3144427/7929520/0853fc2c-08cd-11e5-9faf-c06a940e52f6.png)
So from my test, it looks like a spacing issue. I'll have to put together an OpenFL example to be sure, but from looking at the HaxePunk code I suspect it's an OpenFL issue.

**Comment by scriptorum** [comment] 2015-06-02 19:48
I've reproduced this issue in OpenFL, and reported it there: https://github.com/openfl/openfl/issues/698.

**Comment by rpidstryhach** [comment] 2015-06-03 07:26
Yes, I used leading to avoid that overlapping. It was a quick fix for a while and I completely forgot about this, sorry. Thanks!

**Comment by bendmorris** [comment] 2016-09-30 05:16
Closing since this is not an issue with HaxePunk.

**Closed by bendmorris** 2016-09-30 05:16 UTC
