### ISSUE TITLE
Getting started build fails

### ISSUE THREAD

**Issue by Wolfman13** [HaxePunk/HaxePunk#628] opened 2019-10-11 22:39 UTC
- **HaxePunk version:** 4.0.2
- **Target(s):** lime test neko
- **Haxe version:** 4.0.0-rc.5+4a745347f 
- **OpenFL/Lime or NME version:** OpenFL: 8.9.5-LoqcFr; Lime: 7.6.3; NME: 6.0.58

I ran through the getting started tutorial. I installed the github version of HaxePunk. When I run the ```lime test neko``` command I get the following output and there is no window popping up:

`
/home/jeanjacques/haxelib/HaxePunk/git/haxepunk/input/Input.hx:30: characters 34-47 : Warning : This typedef is deprecated in favor of sys.thread.Deque<neko.vm.Deque.T>
/home/jeanjacques/haxelib/HaxePunk/git/haxepunk/input/Input.hx:31: characters 23-36 : Warning : This typedef is deprecated in favor of sys.thread.Deque<neko.vm.Deque.T>
/home/jeanjacques/haxelib/HaxePunk/git/haxepunk/graphics/Image.hx:219: characters 30-45 : scaledWidth: Custom property accessor is no longer supported, please use `set`
/home/jeanjacques/haxelib/HaxePunk/git/haxepunk/graphics/Image.hx:226: characters 31-47 : scaledHeight: Custom property accessor is no longer supported, please use `set`
/home/jeanjacques/haxelib/HaxePunk/git/haxepunk/math/MathUtil.hx:9: characters 37-57 : NUMBER_MAX_VALUE: Custom property accessor is no longer supported, please use `get`
/home/jeanjacques/haxelib/HaxePunk/git/haxepunk/Signal.hx:69: characters 26-42 : In haxe 4, implements Dynamic is only supported on externs
/home/jeanjacques/haxelib/HaxePunk/git/haxepunk/graphics/text/BitmapText.hx:42: characters 8-14 : haxepunk.graphics.text.AlignType should be Int
/home/jeanjacques/haxelib/HaxePunk/git/haxepunk/graphics/text/BitmapText.hx:43: characters 8-13 : haxepunk.graphics.text.AlignType should be Int
/home/jeanjacques/haxelib/HaxePunk/git/haxepunk/graphics/text/BitmapFontAtlas.hx:65: characters 18-22 : Warning : This typedef is deprecated in favor of haxe.xml.Access
/home/jeanjacques/haxelib/HaxePunk/git/haxepunk/input/Input.hx:36: characters 20-25 : Warning : This typedef is deprecated in favor of sys.thread.Deque<neko.vm.Deque.T>
/home/jeanjacques/haxelib/HaxePunk/git/backend/lime/haxepunk/graphics/hardware/opengl/GLInternal.hx:24: characters 57-68 : openfl.display.OpenGLRenderer has no field __context3D
`

**Comment by XANOZOID** [comment] 2019-11-03 05:54
The problem is the Haxe version. We haven't merged the Haxe 4 fixes just yet, probably because Haxe 4 wasn't officially released until like 3 or so days ago. 

We do have fixes for Haxe 4 that will be ready to merge, and yes, the getting started page needs an update. Thanks for your interest in HaxePunk, and sorry it took this long to get back to you.

**Comment by Wolfman13** [comment] 2019-11-03 10:40
Thanks for letting me know. I look forward to playing around with HaxePunk again

**Comment by matrefeytontias** [comment] 2020-01-06 12:33
Can you test again with the current dev branch ?

**Comment by PsionicAlch** [comment] 2020-01-06 14:00
I tested it and I'm happy to say that it worked

**Closed by PsionicAlch** 2020-01-06 14:00 UTC
